replicaCount: 1

image:
  repository: lab-sre-api
  pullPolicy: IfNotPresent
  tag: v2

service:
  type: NodePort
  port: 8000

config:
  appName: lab-sre-api

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

